services:
  todo-frontend:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-frontend
  mongo:
    image: initialized-mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"] # Overwrite the CMD
    volumes: # Declare the volume
      - ./todo-backend/redis_data:/data
    container_name: redis
  todo-backend:
    image: todo-backend-dev
    volumes:
      - ./todo-backend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      REDIS_URL: //redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
    container_name: todo-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend # wait for the frontend container to be started
      - todo-backend # wait for the backend container to be started
