services:
  todo-frontend:
    image: todo-frontend-dev
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 5173:5173
    container_name: todo-frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend # wait for the frontend container to be started
