services:
  backend:
    image: patientor-backend # This will use the image patientor-backend-dev
    build:
      context: ./backend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: patientor-backend # This will name the container hello-front-dev
  frontend:
    image: patientor-frontend # This will use the image patientor-frontend-dev
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: patientor-frontend # This will name the container hello-front-dev
    depends_on:
      - backend # wait for the backend container to be started
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: patientor-reverse-proxy
    depends_on:
      - frontend # wait for the frontend container to be started
      - backend # wait for the backend container to be started
